### ISSUE TITLE
Override the project selector with a specific project

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-moor-tools-plugin#11]
There are some applications which open QGIS with specific project. There should be a setting in project selector to override the default project loading if the specific project is being loaded by the 3rd party applications.

**Comment by ldebek** [comment]
Looking that ticket and original one from Matt and it seems that such option is implemented already. If you open QGIS project file then project selector window doesn't pop out. Or am I missing something and the use case is somehow different?

**Comment by saberraz** [comment]
@DamnBack that seems to do the trick.
@mtravis is this not what you want?

**Comment by mtravis** [comment]
Yes you're right. Turns out the user was using an older version of the plugin.
