### ISSUE TITLE
Publish the plugin

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-moor-tools-plugin#8]
to a repo!

**Comment by mtravis** [comment]
If you're "going public" with this would it be wise to change the name?

**Comment by saberraz** [comment]
@mtravis sure...do you have any name in mind?

**Comment by mtravis** [comment]
Nothing springs to mind. I'm happy to keep it moor tools if you are.

Be good to see this published. Its been so useful for us.

**Comment by saberraz** [comment]
Published to Lutra repo:
https://qgis.lutraconsulting.co.uk/lutraconsulting/plugins.xml
